Add keypoints/objectives to introduction
esciencecenter-digital-skills/Lesson-FAIR-Data-Climate pull request #14
Opened 2020-10-02 12:46 UTC by stefsmeets

Some more great work with @Peter9192 

Closes #1

2020-10-05 12:52 UTC, Peter9192 commented
@stefsmeets I can't add you as a reviewer for you made this PR, but it would be helpful if you could have a look.
Also at other team members: could you please have a look to see whether this aligns with what you had in mind for the other episodes?

2020-10-05 14:51 UTC, stefsmeets commented
Hi @Peter9192 , nice work! Looks good with the pictures. I made some small adjustments to the text.

2020-10-05 15:02 UTC, Peter9192 commented
> Hi @Peter9192 , nice work! Looks good with the pictures. I made some small adjustments to the text.

Thanks! My editor was complaining about the question marks in headers, but I agree that it looks better if they're included.

2020-10-06 08:46 UTC, nielsdrost requested changes
Nice work @Peter9192 !

See below for comments.

To facilitate comments/suggestions it would help to have every sentence on a single line. However, does that make the max line length checker complain? Do we have one of those? ;-)

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
> +but also for computers. This is relevant especially for data discovery and also
```suggestion
but also for computers. This is especially relevant for data discovery and working with data.
```

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
> +to facilitate working with the data.
```suggestion

```

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
> +(FAIR vs. more FAIR) rather than a binary classification (FAIR vs. not FAIR).
```suggestion
(less FAIR vs. more FAIR) rather than a binary classification (FAIR vs. not FAIR).
```

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
> +development of standards across a scientific domain. We will aim to identify
```suggestion
development of standards across a scientific domain, or even changes to the funding model of projects. We will aim to identify
```

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
> +development of standards across a scientific domain. We will aim to identify
A lot of the problems are political rather than technical. We should mention this.

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
> +but also for computers. This is relevant especially for data discovery and also
Tried to improve sentence structure

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
>  ---
```suggestion
FAIR principles are a set of guiding principles, not rules or standards. 
---
```

2020-10-06 08:46 UTC, nielsdrost commented on _episodes/introduction.md
>  ---
I think this is also a key point

2020-10-06 09:19 UTC, Peter9192 commented
> To facilitate comments/suggestions it would help to have every sentence on a single line

Note that you can also select multiple lines for code suggestions by dragging the blue plus sign vertically when selecting a line to comment on.

2020-10-07 08:04 UTC, Peter9192 commented
@nielsdrost can you approve?

2020-10-07 09:55 UTC, nielsdrost approved these changes
Thanks @Peter9192 !

2020-10-07 09:55 UTC, merged